### PR TITLE
busybox: re-enable lsmod/rmmod/insmod/modprobe to fix stubdomain init…

### PR DESCRIPTION
**Pull request by cjp256**
…ramfs

Signed-off-by: Chris Patterson pattersonc@ainfosec.com

### CODE REVIEW

**Comment by aikidokatech** [comment]
This should be causing a conflict with kmod.  Also, modprobe from busybox may not support -a, which is used in one of our scripts. (i915)  Kmod's modprobe does support -i.

**Comment by aikidokatech** [comment]
Also, the /init file in stubdomain references modprobe in busybox-static.  Looks like the intention was that stubdomain used busybox-static like xenclient-initramfs-image does.

**Comment by cjp256** [comment]
I believe this matches current behavior.  Both versions of modprobe are installed, but update-alternatives defaults to using the kmod version as it has higher priority.  So the i915 script still works as expected.

**Comment by cjp256** [comment]
Also, I would discourage making the change to busybox-static unless otherwise required.  It's probably best to match OpenXT's current setup.  The comment could just be outdated cruft.  The only user of it I see current in openxt/master is the dom0 initramfs.

**Comment by aikidokatech** [comment]
The turning off of the module utilities in busybox-static is actually a change from OpenXT mainline.  Being that stubdomain is an initramfs, wouldn't it be better to use the statically linked busybox?

**Comment by cjp256** [comment]
I agree with that, I originally set them in -static as well, but did not commit those changes because it wasn't causing me issues. I can commit that too if you want.

As far as whether or not it would be better to use -static, I don't know, because I'm not entirely sure why it exists :) Personally, I'd rather drop -static entirely (core-image-minimal-initramfs seems to manage OK).  I can investigate that separately.

**Comment by aikidokatech** [comment]
So far I believe it is only for the module utilities.  We could also do the same thing with kmod I supposed.  I've never tried to sit down and really look at what the initramfs is doing to see if it can be changed for the better.  I've only been looking at things from an OE meta-data perspective.  If you want change the pull request, adding the changes only to busybox-static and having stubdomain-initramfs use that, I would move forward with that.

**Comment by cjp256** [comment]
As far as -static is concerned, I submitted a PR to drop it entirely from OpenXT:
https://github.com/OpenXT/xenclient-oe/pull/180

**Pull request merged**
