### PR TITLE
Fix do_install failures on libsepol.

### PR DESCRIPTION
**Pull request by ktemkin**
This really should be fixed in meta-selinux, but this will do until @cjp256 convinces upstream to accept a fix.

### CODE REVIEW

**Comment by ktemkin** [comment]
Generally, recipes are built with a `PATH` that prefers using binaries from the build sysroot over any local copies-- it was originally using the host's `ln` only because `ln` didn't exist in the sysroot.

Once it builds `coreutils-native`, a newer copy of `ln` will exist in the build sysroot, and will be used automatically.

**Comment by aikidokatech** [comment]
Guess I forgot to hit comment last time.
Should we just go ahead and patch libselinux.inc also?

https://www.mail-archive.com/yocto@yoctoproject.org/msg26230.html

**Comment by ktemkin** [comment]
Updated to include libselinux.

**Comment by cjp256** [comment]
I replied to an earlier thread, no noise.

https://lists.yoctoproject.org/pipermail/yocto/2015-November/027463.html

**Pull request merged**
