### PR TITLE
Jethro various fixes

### PR DESCRIPTION
**Pull request by cjp256**

### CODE REVIEW

**Comment by aikidokatech** [comment]
Can you drop the pseudo portion?  The Jethro branch is using upstream pseudo 1.7.4.

**Comment by cjp256** [comment]
Awesome, will fix.

**Comment by cjp256** [comment]
Fixed!

**Comment by aikidokatech** [comment]
Also, I think the xenclient-initramfs defconfig was supposed to be in a folder called xenclient-stubdomain.  That defconfig would only get used when the machine name matches and the initramfs uses xenclient-dom0.  We can probably drop that folder in a commit that also ditches busybox static.  Anyways, merging PR.

**Pull request merged**
